version: '3.8'
services:
  myapp:
    container_name: adoring_solomon
    image: myapp
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 8000:8000
    # volumes:
    #   - ./mongodb_volume:/data/db