version: '3.8'
services:
  myapp:
    container_name: myapp-container-name
    image: myapp
    restart: always
    environment:
      RUST_DOCKER_NAME: ${RUST_DOCKER_NAME}
    ports:
      - 8000:8000
    # volumes:
    #   - ./mongodb_volume:/data/db